extends Node

var INTERROGATION1_VIEWED = false
var INTERROGATION2_VIEWED = false
var MINIGAME_TELEPHONE_COMPLETED = false
var MINIGAME_CASAINCENTRO_COMPLETED = false
var CURRENT_MINIGAME = null
var INTERROGA = null
