extends ColorRect

var DESC = {
	"en":[
		"Good fortune awaits in the near future.",
		"Don't rush into important matters.",
		"Be attentive to details.",
		"Good news is expected soon.",
		"Great inspiration is expected.",
		"Be careful what you say.",
		"Do not jump to conclusions.",
		"It is important to have patience.",
		"The fate is favorable to you.",
		"You will gain valuable experience.",
		"Your work will be fruitful.",
		"Your mistakes will make you stronger.",
		"Lose friends if you start looking for flaws in them.",
		"Ignore possible provocations.",
		"Problems at work will eventually turn into success.",
		"Don't try to do two things at the same time.",
		"There will be a difficult choice.",
		"Fate will give you a second chance.",
		"You will need help to catch your luck.",
		"A stranger will help you in business."
	],
	"ru":[
		"В ближайшее время ожидает удача.",
		"Не торопись с решением важных дел.",
		"Будь внимателен к деталям.",
		"В скором времени ожидаются хорошие новости.",
		"Ожидается большое вдохновение.",
		"Будьте осторожны в словах.",
		"Не делайте поспешных выводов.",
		"Важно запастись терпением.",
		"Судьба к вам благосклонна.",
		"Вы приобретёте ценный опыт.",
		"Ваш труд будет плодотворным.",
		"Ваши ошибки сделают вас сильнее.",
		"Потеряете друзей, если начнёте искать в них изъяны.",
		"Игнорируйте возможные провокации.",
		"Проблемы на работе в итоге выльются в успех.",
		"Не хватайтесь за два дела одновременно.",
		"Предстоит нелёгкий выбор.",
		"Судьба подарит вам второй шанс.",
		"Чтобы поймать удачу, потребуется помощь.",
		"Незнакомец поможет вам в делах."
	],
	"zh":[
		"好运在不久的将来等待着你。",
		"不要急于处理重要事务。",
		"要注意细节。",
		"预计很快会有好消息。",
		"预计会有巨大的灵感。",
		"小心你说的话。",
		"不要轻易下结论。",
		"重要的是要有耐心。",
		"命运对你是有利的。",
		"你将获得宝贵的经验。",
		"你的工作将富有成效。",
		"你的错误会让你更强大。",
		"如果你开始在他们身上寻找缺点，就会失去朋友。",
		"忽略可能的挑衅。",
		"工作中的问题最终会转化为成功。",
		"不要试图同时做两件事。",
		"会有一个困难的选择。",
		"命运会给你第二次机会。",
		"你将需要帮助来抓住你的运气。",
		"一个陌生人会在生意上帮助你。"
	]
}
